import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // Plain Node CommonJS scripts - require() is the module system here.
    files: ["**/*.cjs"],
    rules: { "@typescript-eslint/no-require-imports": "off" },
  },
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Not this app's own Next.js code:
    "templates/**", // scaffolding for generated apps (frozen builder)
    "supabase/functions/**", // Deno edge functions
    "public/embed.js", // hand-written browser embed loader
    "lib/apps/baseTemplate.generated.ts", // generated by `npm run gen:base`
  ]),
]);

export default eslintConfig;
