import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // React Compiler-era rules that eslint-config-next 16 turned on as errors.
    // The existing admin/workspace components predate them (mostly
    // setState-in-effect data loading); fixing them changes component
    // behaviour, so they warn for now and get fixed file by file.
    // Same files glob as eslint-config-next's block that loads the plugin.
    files: ["**/*.{js,jsx,mjs,ts,tsx,mts,cts}"],
    rules: {
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/purity": "warn",
      "react-hooks/immutability": "warn",
      "react-hooks/use-memo": "warn",
      "react-hooks/preserve-manual-memoization": "warn",
    },
  },
  {
    // Plain Node CommonJS scripts - require() is the module system here.
    files: ["**/*.cjs"],
    rules: { "@typescript-eslint/no-require-imports": "off" },
  },
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Not this app's own Next.js code:
    "templates/**", // scaffolding for generated apps (frozen builder)
    "supabase/functions/**", // Deno edge functions
    "public/embed.js", // hand-written browser embed loader
    "lib/apps/baseTemplate.generated.ts", // generated by `npm run gen:base`
  ]),
]);

export default eslintConfig;
