import { NextRequest, NextResponse } from "next/server";
import { createServerClient, createServiceClient } from "@/lib/supabase";
import { parseFileList } from "@/lib/apps/fileMap";
import { zipSync, csvRow, type ZipEntry } from "@/lib/zip";

export const runtime = "nodejs";
export const maxDuration = 120;

const MGMT_TOKEN = process.env.SUPABASE_MANAGEMENT_TOKEN;
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_REF = new URL(SUPABASE_URL).hostname.split(".")[0];
const MAX_ROWS_PER_TABLE = 50_000;

async function runSql(sql: string): Promise<Record<string, unknown>[]> {
  if (!MGMT_TOKEN) return [];
  const res = await fetch(
    `https://api.supabase.com/v1/projects/${SUPABASE_REF}/database/query`,
    {
      method: "POST",
      headers: { Authorization: `Bearer ${MGMT_TOKEN}`, "Content-Type": "application/json" },
      body: JSON.stringify({ query: sql }),
    },
  );
  if (!res.ok) return [];
  const body = await res.json();
  return Array.isArray(body) ? body : [];
}

function tableToCsv(rows: Record<string, unknown>[]): string {
  if (rows.length === 0) return "";
  const cols = Object.keys(rows[0]);
  const lines = [csvRow(cols)];
  for (const r of rows) lines.push(csvRow(cols.map((c) => r[c])));
  return lines.join("\r\n");
}

// GET — a zip of the app's full source + a CSV dump of its database.
// The escape hatch: the customer can take this and self-host.
export async function GET(
  _req: NextRequest,
  props: { params: Promise<{ appId: string }> },
) {
  const { appId } = await props.params;

  const supabase = await createServerClient();
  const {
    data: { user },
    error: authError,
  } = await supabase.auth.getUser();
  if (authError || !user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { data: app } = await createServiceClient()
    .from("apps")
    .select("id, user_id, name, generated_code, deploy_url")
    .eq("id", appId)
    .single();
  if (!app || app.user_id !== user.id) {
    return NextResponse.json({ error: "App not found" }, { status: 404 });
  }
  if (!app.generated_code) {
    return NextResponse.json({ error: "This app has no source yet." }, { status: 409 });
  }

  const slug =
    app.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 40) || "app";

  const entries: ZipEntry[] = [];

  // 1. Source
  for (const f of parseFileList(app.generated_code)) {
    entries.push({ name: `app-source/${f.path}`, data: f.content });
  }

  // 2. Data — every base table in the tenant schema
  const schema = `app_${appId.slice(0, 8)}`;
  const tables = await runSql(
    `select table_name from information_schema.tables
       where table_schema = '${schema}' and table_type = 'BASE TABLE'
       order by table_name`,
  );
  const exported: string[] = [];
  for (const t of tables) {
    const name = String(t.table_name);
    if (!/^[a-z0-9_]+$/i.test(name)) continue;
    const rows = await runSql(
      `select * from "${schema}"."${name}" limit ${MAX_ROWS_PER_TABLE}`,
    );
    entries.push({ name: `data/${name}.csv`, data: tableToCsv(rows) });
    exported.push(`${name} (${rows.length} rows)`);
  }

  // 3. README
  entries.push({
    name: "EXPORT_README.md",
    data: [
      `# ${app.name} — export`,
      "",
      `Generated by VisionWorkx on ${new Date().toISOString().slice(0, 10)}.`,
      app.deploy_url ? `Live copy: ${app.deploy_url}` : "",
      "",
      "## Contents",
      "- `app-source/` — the complete Next.js + Supabase source, including",
      "  `supabase/migrations/` (the schema) and `.env.local.example`.",
      "- `data/` — a CSV per database table" +
        (exported.length ? `: ${exported.join(", ")}.` : " (none had rows)."),
      "",
      "## Running it yourself",
      "1. Create a Supabase project and run the SQL in `app-source/supabase/migrations/`.",
      "2. Import each `data/*.csv` into its table.",
      "3. Copy `.env.local.example` to `.env.local` and fill in your Supabase keys.",
      "4. `npm install && npm run dev`, then deploy anywhere that runs Next.js.",
      "",
      "This is your data and your code — no lock-in.",
    ]
      .filter(Boolean)
      .join("\n"),
  });

  const zip = zipSync(entries);
  return new Response(new Uint8Array(zip), {
    headers: {
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="${slug}-export.zip"`,
      "Cache-Control": "no-store",
    },
  });
}
